// engine/registry.js
// Resolves session names to UUIDs by scanning ~/.copilot/session-state/*/workspace.yaml.
//
// We deliberately do NOT use the SQLite session-store.db — too brittle (locking,
// schema changes). The yaml file is the source of truth on disk per-session.

const fs = require('fs');
const path = require('path');
const os = require('os');

const SESSION_STATE = path.join(os.homedir(), '.copilot', 'session-state');

// Tiny YAML reader — we only need top-level "key: value" lines.
// The session workspace.yaml is generated by VS Code and is shallow.
function parseShallowYaml(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, '').trim();
    if (!line) continue;
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!m) continue;
    let val = m[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (val === 'true') val = true;
    else if (val === 'false') val = false;
    out[m[1]] = val;
  }
  return out;
}

function readSessionMeta(uuid) {
  const dir = path.join(SESSION_STATE, uuid);
  const yamlPath = path.join(dir, 'workspace.yaml');
  if (!fs.existsSync(yamlPath)) return null;
  let meta;
  try {
    meta = parseShallowYaml(fs.readFileSync(yamlPath, 'utf8'));
  } catch { return null; }
  return {
    uuid,
    name: meta.name || null,
    cwd: meta.cwd || null,
    repository: meta.repository || null,
    branch: meta.branch || null,
    user_named: meta.user_named === true || meta.user_named === 'true',
    folder: dir,
  };
}

/**
 * List all known sessions. Optionally filter by workspace cwd.
 * @param {object} [opts]
 * @param {string} [opts.workspace]  Absolute path; only return sessions matching this cwd.
 * @returns {Array<{uuid,name,cwd,...}>}
 */
function list(opts = {}) {
  if (!fs.existsSync(SESSION_STATE)) return [];
  const result = [];
  for (const entry of fs.readdirSync(SESSION_STATE, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const meta = readSessionMeta(entry.name);
    if (!meta) continue;
    if (opts.workspace && normalize(meta.cwd) !== normalize(opts.workspace)) continue;
    result.push(meta);
  }
  return result;
}

function normalize(p) {
  if (!p) return '';
  return path.resolve(p).toLowerCase();
}

/**
 * Resolve a session by name (or UUID directly). Workspace-scoped by default.
 * Throws when ambiguous or not found.
 *
 * @param {string} target  Either a session name like "PM" or a session UUID
 * @param {object} [opts]
 * @param {string} [opts.workspace]  Workspace cwd to scope name lookups to
 * @returns {{uuid,name,cwd,...}}
 */
function resolve(target, opts = {}) {
  if (!target) throw new Error('target is required');

  // If target looks like a UUID, try as-is.
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(target)) {
    const meta = readSessionMeta(target);
    if (meta) return meta;
    throw new Error(`No session with UUID ${target}`);
  }

  const candidates = list({ workspace: opts.workspace }).filter(s => s.name === target);
  if (candidates.length === 0) {
    const scope = opts.workspace ? ` in workspace ${opts.workspace}` : '';
    throw new Error(`No session named "${target}"${scope}`);
  }
  if (candidates.length > 1) {
    throw new Error(
      `Ambiguous session name "${target}" — matches ${candidates.length} sessions: ` +
      candidates.map(c => c.uuid).join(', ')
    );
  }
  return candidates[0];
}

module.exports = { list, resolve, readSessionMeta, SESSION_STATE };
